### ISSUE TITLE
[REQUEST] Add same PyPa workflow as the other zigpy projects

### ISSUE THREAD

**Issue by Hedda** [zha-ng/zha-map#20]
PyPa has a GitHub Action for publishing pre-built distribution packages to PyPI.

- https://github.com/pypa/gh-action-pypi-publish

Consider adding PyPa workflow in the same unified way as other zigpy libraries, see:
 
- https://github.com/zigpy/zigpy-deconz/pull/98

and

- https://github.com/zigpy/zigpy/pull/336
  - https://github.com/zigpy/zigpy/pull/338

Also, consider adding a long description to PyPi index by pointing to the README.md

- https://github.com/zigpy/zigpy/pull/371

Keeping this and other information the same in all zigpy libraries can help unify them.

**Comment by Adminiuga** [comment]
Zha-map is not a python package and is not published to pypi.
