### ISSUE TITLE
Select different types of links

### ISSUE THREAD

**Issue by meremortals70** [zha-ng/zha-map#22]
Would it be possible to add a facility which would allow us to select the different type of links.

Eg. All green links, or all red links?

It would allow a cleaner view when trying to optimise our networks.

**Comment by meremortals70** [comment]
> Would it be possible to add a facility which would allow us to select the different type of links.
> 
> 
> 
> Eg. All green links, or all red links?
> 
> 
> 
> It would allow a cleaner view when trying to optimise our networks.

So nothing, I guess I will be going back to Deconz.

**Comment by RoldyBuffalo** [comment]
> 
> 
> > Would it be possible to add a facility which would allow us to select the different type of links.
> > Eg. All green links, or all red links?
> > It would allow a cleaner view when trying to optimise our networks.
> 
> So nothing, I guess I will be going back to Deconz.

I assume you mean optimize the network. I would also argue that a map, any zig-bee or Zha map is purely for informational purposes. If you are wanting to see clearer views of what is and what is not properly connected, take a peek at the neighbors.yaml file. It has all the information you need, no map required. 

Furthermore, if by optimize you mean reduce interference? Well, maybe take a look at your wifi channel in comparison to your Zig-bee channel. If they overlap, and yes they can overlap; you will continue to see issues until that interference from your wifi is resolved.

hope this helps!

regards,

Roldy
