### ISSUE TITLE
doesn't install

### ISSUE THREAD

**Issue by oldfart101** [zha-ng/zha-map#23]
HA v. 0.114.4 (on Raspberry Pi 4) 
added repository:
Says Unknown
No installation option in Add-On store

**Comment by walthowd** [comment]
You can use HACS and add zha-map as a custom repository.

**Comment by oldfart101** [comment]
added repository, it doesn't show up in the Home Assistant Community Add-ons

**Comment by walthowd** [comment]
You might try the HACS help or discord (chat) here:

https://hacs.xyz/help

They should be able to help you get it going

**Comment by oldfart101** [comment]
![image](https://user-images.githubusercontent.com/27557414/93098349-aca54780-f69e-11ea-89b1-6c17cb8b8bb0.png)

**Comment by walthowd** [comment]
Looks like you are in the Hass.io add on store, not in HACS. 

See here for installing HACS:
https://hacs.xyz/docs/installation/prerequisites

**Comment by Adminiuga** [comment]
Yes, this is not a Hass.io add-on. It is present only in HACS.
