### ISSUE TITLE
How to use this component?

### ISSUE THREAD

**Issue by Anonym-tsk** [zha-ng/zha-map#3]

**Comment by Adminiuga** [comment]
It is pretty much a pre-alfa ATM. No support, as-is.
in a nutshell:

- add it as a custom component. in the folder where is your `configuration.yaml` you need to create `custom_components` and copy [zha-map](folder) there https://github.com/zha-ng/zha-map/tree/dev/custom_components/zha_map eg `/config/custom_components/zha_map`

- add `zha_map:` to `configuration.yaml` and restart HA. 

- then add the custom card found here: https://github.com/dmulcahey/zha-network-visualization-card  and in your lovelace config add: 
```
resources:
  - type: module
    url: /local/zha-network-visualization-card.js
```

- add `'custom:zha-network-visualization-card'` custom card to love lace card, better in the panel mode.

the zha map component will build out the info over time. There's about 20min delay after the start and then every few hours it rescans again. If you  don't want to wait you can run the `zha_map.scan_now` service in the services developer tool and that will build out the data needed for the visualization. Would take some time, depending if any devices are offline and on a number of devices.


I recommend adding the card to its own view and turning on panel mode

**Comment by Anonym-tsk** [comment]
I think, you have to write this to readme.md 👍 Thank you.

**Comment by Adminiuga** [comment]
PRs are welcome.

**Comment by jamescadd** [comment]
Would you consider adding this to HACS to make installation easier?  It seems like you're actively working on it.

**Comment by Adminiuga** [comment]
![image](https://user-images.githubusercontent.com/5826160/85480811-a49da600-b58e-11ea-86b2-6c05b42b7baa.png)

**Comment by jamescadd** [comment]
Thanks for the pointer, that works well.  If you wanted to setup the Information tab it may help folks getting started, but if they already knew enough to search for the repo then they can probably figure that out :)

![image](https://user-images.githubusercontent.com/2729218/85813606-7ea40d00-b718-11ea-9d7b-9a9c9a9d4a59.png)

**Comment by mrneutron42** [comment]
In the step "add zha_map: to configuration.yaml and restart HA."

What kind of Home Assistant object or entity does this create,, with just a name and a colon? 

Most of the custom_components  I've added to the configuration.yaml file are a "- platform:" entry.

Thanks for any clarification.

**Comment by Adminiuga** [comment]
It does not create any entities. It just creates a web socket for the lovelace card.
In configuration.yaml you just add `zha_map:` on its own line, to tell ha to load this as an integration

**Comment by Adminiuga** [comment]
FYI, check Zigbee channel on HA discord server. Usually there are a few people knowing answers or hints.
