### ISSUE TITLE
Missing zigbee device

### ISSUE THREAD

**Issue by hellcry37** [zha-ng/zha-map#38]
Logger: custom_components.zha_map.neighbour
Source: custom_components/zha_map/neighbour.py:98
Integration: ZHA Network Map (documentation)
First occurred: 8:45:12 AM (6 occurrences)
Last logged: 8:47:25 AM

    [00:17:88:01:04:fd:7c:e5]: neighbour f0:d1:b8:00:00:10:c4:63 is not in 'zigbee.db'
    [00:17:88:01:04:17:cc:fe]: neighbour f0:d1:b8:00:00:10:c4:63 is not in 'zigbee.db'
    [00:17:88:01:04:fd:7b:b7]: neighbour f0:d1:b8:00:00:10:c4:63 is not in 'zigbee.db'

I keep getting those warnings after I removed a Osram Bulb (f0:d1:b8:00:00:10:c4:63) from the network. This should not happen since the device is not there anymore from 3 days.

Steps I did to fix the issue:
- restarted (powercycle) all zigbee routers
- restarted home assistant many times

**Comment by Adminiuga** [comment]
If you know that you removed that device, then just ignore this message. The devices on your network still report the device from their neighbor table and zha map is just relaying this info to you.
