### ISSUE TITLE
setup directions not working in October 2020 version of Home Assistant

### ISSUE THREAD

**Issue by mrneutron42** [zha-ng/zha-map#39]
I'm getting this error when I try and create a custom card.
![error zha-network-visualization-card](https://user-images.githubusercontent.com/70338169/96355527-223e7200-10a8-11eb-9c6d-2a4eeef945e7.PNG)
I followed the directions in the wiki as closely as I could.  
I note that the terminology in the directions doesn't match the menu choices and button names in the current (2020) version of Home Assistant.   
I'm betting the UI has changed since the directions were written?
For example, the is no "Configure UI" choice in the ⋮ circle, only "Edit Dashboard".
![Edit Dashboard](https://user-images.githubusercontent.com/70338169/96370469-8baf9680-1123-11eb-9558-3e9e80406768.PNG)
After that, there are 2 + buttons to choose from:  
1. the upper + button is Add View
![Lovelace + button Add view](https://user-images.githubusercontent.com/70338169/96370487-99fdb280-1123-11eb-93f9-47ebb40f701e.PNG)

2. the lower + button is Add Card
![Lovelace + button Add Card](https://user-images.githubusercontent.com/70338169/96370495-9f5afd00-1123-11eb-8a87-0312b5927ed4.PNG)

Which + button do we choose in the current (2020) versions of Home Assistant?

I'm running HA in a VMWare Virtual Machine:
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.14
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.69
python_version | 3.8.5
supervisor | 247
timezone | America/Chicago
version | 0.116.4
virtualenv | false

**Comment by Adminiuga** [comment]
Try asking in Zigbee channel on home assistant discord channel. Zha map is independent of the lovelace card.
