### ISSUE TITLE
Not working on Home Assistant 0.115.2

### ISSUE THREAD

**Issue by paoloach** [zha-ng/zha-map#40]
Hi,
I tried to use your component but I got an error like undefined record.device_type and so on.

It seems that that HA version use a difference version of zigpy you expected because I had to change some lineof code  as the follow patch file.
[fix_for_HA_0_115_2.zip](https://github.com/zha-ng/zha-map/files/5410828/fix_for_HA_0_115_2.zip)

**Comment by Adminiuga** [comment]
Don't use latest version of zha_map or upgrade to ha .0.116.x

**Comment by Adminiuga** [comment]
HA 0.115.4 and later should use latest zha-map
Previous HA versions should use different older zha-map versions. 
There were some incompatible changes upstream.
This project is no longer maintained.
