### ISSUE TITLE
LQI reported false in neighbor files

### ISSUE THREAD

**Issue by Repsionu** [zha-ng/zha-map#41]
HA latest on real core (venv), coordinator is Tasmotized ZbBridge in ZHA mode. Neighbor files report false LQI versus ZHA data (and real world distance) e.g. device with LQI=255 reports 0 :-(
No big problem of course but very nice ZigZag reports false colors for LQI :-)
Done some zha_map service rescans but no luck...
If needed can show LQI differences in neighbor file vs ZHA data.
Best, JR

**Comment by Adminiuga** [comment]
Enable debug logging and compare what device actually reports vs what is in the file.

**Comment by Repsionu** [comment]
OK will do tommorow, too late today 👍 
Debug logging You mean... All Zigbee stuff? Now no errors in logs :-)

**Comment by Adminiuga** [comment]
There won't be errors, but all lqi information is coming from zdo mgmt_lqi_rsp messages, so just compare that those contain right information

**Comment by Repsionu** [comment]
Did some further tests- still no go :-(
Added my ZHA device info and some neighbor files:
![ZigBee LQI](https://user-images.githubusercontent.com/46962963/97751681-5def2800-1afb-11eb-8bb2-9979c08484e9.png)
[neighbours_60a423fffe1dbdc1.txt](https://github.com/zha-ng/zha-map/files/5467377/neighbours_60a423fffe1dbdc1.txt)
[neighbours_00124b001e731acb.txt](https://github.com/zha-ng/zha-map/files/5467378/neighbours_00124b001e731acb.txt)
[neighbours_00124b001e73198a.txt](https://github.com/zha-ng/zha-map/files/5467379/neighbours_00124b001e73198a.txt)
[neighbours_00124b001e722554.txt](https://github.com/zha-ng/zha-map/files/5467380/neighbours_00124b001e722554.txt)
Maybe :-)
Best, JR

**Comment by Adminiuga** [comment]
1. those are different LQI and unlikely to be the same. ZHA reports LQI as seen by the coordinator from the "last hop", eg Device -> [hop] -> [last hop] -> coordinator -- it shows LQI for the messaged relayed by the last hop.

2. ZHA MAP reports LQI as reported by the device for its particular neighbor.

Unless you can show in the logs that ZDO Mgmt_Lqi_rsp contains different data/LQI for a particular neighbor then i

**Comment by Repsionu** [comment]
So for "multihop" or lots of routers to extend range we can not use :-( ?
All graphing is uniformative... OK, then so it is :-)
Best, JR
